2025-05-26 16:04:40.250 | INFO     | main:websocket_endpoint:29 - WebSocket connection accepted from 127.0.0.1:53452
2025-05-26 16:04:40.251 | ERROR    | main:websocket_endpoint:65 - Error in WebSocket handler for 127.0.0.1:53452: 'FileOperatorTool' object has no attribute '__pydantic_fields_set__'
2025-05-26 16:04:40.251 | INFO     | main:websocket_endpoint:75 - Cleaned up resources for 127.0.0.1:53452
